# This workflow executes several linters on changed files based on languages used in your code base whenever
# you push a code or open a pull request.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/github/super-linter
name: Lint Code Base

on:
  pull_request:
    branches: [ master ]
jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Run check style
        uses: nikitasavinov/checkstyle-action@master
        with:          
          github_token: ${{ secrets.GITHUB_TOKEN }}
          checkstyle_config: .checkstyle/checkstyle.xml
          tool_name: 'SPACES CHECK with checkstyle'
          level: warning
          filter_mode: added
