name: checkstyle stats collection

on:
  pull_request:
    branches: [ master ]
jobs:
  run-checkstyle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run check style
        id: checkStyle
        uses: dadams2/checkstyle-action@master
        with:          
          github_token: ${{ secrets.GITHUB_TOKEN }}
          checkstyle_config: .checkstyle/checkstyle.xml          
          filter_mode: added      
