name: Test Actions
on:
  push:
    branches: [ master ]
jobs:
  test-stuff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0    
      - name: Set the value
        id: step_one
        run: |
            echo "FOO=$(date)" >> $GITHUB_ENV
      - name: Use the value
        id: step_two
        run: |
            echo "${{ env.FOO }}"
